# Automatically generated by Text-Smart.spec.PL

%define perlsitearch %(perl -e 'use Config; print $Config{installsitearch}')
%define perlsitelib %(perl -e 'use Config; print $Config{installsitelib}')
%define perlsiteprefix %(perl -e 'use Config; print $Config{siteprefix}')
%define perlsiteman3 %{perlsiteprefix}/share/man/man3
%define perlversion %(perl -e 'use Config; print $Config{version}')

%define appname Text-Smart

Summary: Text::Smart - Simple text markup processor
Name: perl-%{appname}
Version: 1.0.0
Release: 1
Copyright: GPL
Group: Applications/Internet
Source: %{appname}-%{version}.tar.gz
BuildRoot: /var/tmp/%{appname}-%{version}-root
BuildArchitectures: noarch
Requires: perl = %{perlversion}

%description
Text::Smart provides a module for simple inline text
markup processing.
 
%prep
%setup -q -n %{appname}-%{version}


%build
perl Makefile.PL PREFIX=$RPM_BUILD_ROOT/usr
make


%install
rm -rf $RPM_BUILD_ROOT
make install INSTALLSITEMAN3DIR=$RPM_BUILD_ROOT%{perlsiteman3}
find $RPM_BUILD_ROOT%{perlsitearch} -name perllocal.pod -exec rm -f {} \;

%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root)
%doc AUTHORS
%doc COPYING
%doc README
%{perlsiteman3}/*
%{perlsitelib}/Text/Smart.pm
%{perlsitelib}/Text/Smart/
%{perlsitearch}/auto/Text/Smart/
